"""Predefined locations for the job search filter."""

US_STATES = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
    "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
    "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico", "New York",
    "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
    "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia",
    "Washington", "Washington, DC", "West Virginia", "Wisconsin", "Wyoming",
]

MAJOR_CITIES = [
    "San Francisco, CA",
    "South San Francisco, CA",
    "Palo Alto, CA",
    "Mountain View, CA",
    "Sunnyvale, CA",
    "San Jose, CA",
    "Berkeley, CA",
    "Oakland, CA",
    "San Diego, CA",
    "Los Angeles, CA",
    "Sacramento, CA",
    "Seattle, WA",
    "Portland, OR",
    "Boston, MA",
    "Cambridge, MA",
    "New York, NY",
    "Brooklyn, NY",
    "Princeton, NJ",
    "Jersey City, NJ",
    "Philadelphia, PA",
    "Pittsburgh, PA",
    "Washington, DC",
    "Baltimore, MD",
    "Raleigh, NC",
    "Durham, NC",
    "Charlotte, NC",
    "Atlanta, GA",
    "Chicago, IL",
    "Austin, TX",
    "Houston, TX",
    "Dallas, TX",
    "Denver, CO",
    "Phoenix, AZ",
    "Miami, FL",
    "Minneapolis, MN",
    "Detroit, MI",
    "Salt Lake City, UT",
    "Nashville, TN",
]

REMOTE_LABEL = "Remote (US)"
